### ISSUE TITLE
Cannot receive SMS OTP on STAGE site after Success response

### ISSUE THREAD

**Issue by shortstopyomin** [ECPay/ECPayMobileSDK_Android#1]
response : {"MerchantID":"2000132","MerchantTradeNo":"20161016160851654","TradeNo":"1610161608500142","RtnCode":"3","RtnMsg":"Create+Trade+Success","TradeDate":"2016/10/16 16:08:50","OtpExpiredTime":"2016/10/16 16:18:50"}

D/AllpayMobileSDK: AllpayAsyncTask.onPostExecute -> {"MerchantID":"2000132","MerchantTradeNo":"20161016160851654","OtpExpiredTime":"2016/10/16 16:18:50","TradeDate":"2016/10/16 16:08:50","TradeNo":"1610161608500142","RtnCode":3,"RtnMsg":"Create+Trade+Success"}

**Comment by AllennChang** [comment]
你好.相關使用問題請您寄信到我們技術客服信箱 techsupport@greenworld.com.tw ,會有專人為您服務解答
